package pojos;
// Generated 30.5.2017 9:48:40 by Hibernate Tools 4.3.1

/**
 * ValueTbl generated by hbm2java
 */
public class ValueTbl implements java.io.Serializable {

    private Integer idValue;
    private String type;
    private int value1;
    private int value2;
    private int value3;
    private int value4;
    private int value5;
    private int value6;
    private int value7;
    private int value8;
    private int value9;
    private int value10;
    /**
     * Konstruktor triedy ValueTbl
     */
    public ValueTbl() {
    }
    /**
     * Konstruktor triedy ValueTbl
     * @param type typ senzoru
     @param value1 prva hodnota senzoru 
     * @param value2 druha hodnota senzoru 
     * @param value3 tretia hodnota senzoru 
     * @param value4 stvrta hodnota senzoru 
     * @param value5 piata hodnota senzoru 
     * @param value6 siesta hodnota senzoru 
     * @param value7 siedma hodnota senzoru 
     * @param value8 osma hodnota senzoru 
     * @param value9 deviata hodnota senzoru 
     * @param value10 desiata hodnota senzoru 
     */
    public ValueTbl(String type, int value1, int value2, int value3, int value4, int value5, int value6, int value7, int value8, int value9, int value10) {
        this.type = type;
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
        this.value5 = value5;
        this.value6 = value6;
        this.value7 = value7;
        this.value8 = value8;
        this.value9 = value9;
        this.value10 = value10;
    }
    /**
     * geter
     * @return vrati ID senzoru
     */
    public Integer getIdValue() {
        return this.idValue;
    }
    /**
     * seter
     * @param idValue ID senzoru
     */
    public void setIdValue(Integer idValue) {
        this.idValue = idValue;
    }
     /**
     * geter
     * @return vrati typ senzoru
     */
    public String getType() {
        return this.type;
    }
    /**
     * seter
     * @param type typ senzoru
     */
    public void setType(String type) {
        this.type = type;
    }
     /**
     * geter
     * @return vrati hodnotu1 senzoru
     */
    public int getValue1() {
        return this.value1;
    }
    /**
     * seter
     * @param value1 hodnota1
     */
    public void setValue1(int value1) {
        this.value1 = value1;
    }
    /**
     * geter
     * @return vrati hodnotu2 senzoru
     */
    public int getValue2() {
        return this.value2;
    }
    /**
     * seter
     * @param value2 hodnota2
     */
    public void setValue2(int value2) {
        this.value2 = value2;
    }
    /**
     * geter
     * @return vrati hodnotu3 senzoru
     */
    public int getValue3() {
        return this.value3;
    }
    /**
     * seter
     * @param value3 hodnota3
     */
    public void setValue3(int value3) {
        this.value3 = value3;
    }
    /**
     * geter
     * @return vrati hodnotu4 senzoru
     */
    public int getValue4() {
        return this.value4;
    }
    /**
     * seter
     * @param value4 hodnota4
     */
    public void setValue4(int value4) {
        this.value4 = value4;
    }
    /**
     * geter
     * @return vrati hodnotu5 senzoru
     */
    public int getValue5() {
        return this.value5;
    }
    /**
     * seter
     * @param value5 hodnota5
     */
    public void setValue5(int value5) {
        this.value5 = value5;
    }
    /**
     * geter
     * @return vrati hodnotu6 senzoru
     */
    public int getValue6() {
        return this.value6;
    }
    /**
     * seter
     * @param value6 hodnota6
     */
    public void setValue6(int value6) {
        this.value6 = value6;
    }
    /**
     * geter
     * @return vrati hodnotu7 senzoru
     */
    public int getValue7() {
        return this.value7;
    }
    /**
     * seter
     * @param value7 hodnota7
     */
    public void setValue7(int value7) {
        this.value7 = value7;
    }
    /**
     * geter
     * @return vrati hodnotu8 senzoru
     */
    public int getValue8() {
        return this.value8;
    }
    /**
     * seter
     * @param value8 hodnota8
     */
    public void setValue8(int value8) {
        this.value8 = value8;
    }
    /**
     * geter
     * @return vrati hodnotu9 senzoru
     */
    public int getValue9() {
        return this.value9;
    }
    /**
     * seter
     * @param value9 hodnota9
     */
    public void setValue9(int value9) {
        this.value9 = value9;
    }
    /**
     * geter
     * @return vrati hodnotu10 senzoru
     */
    public int getValue10() {
        return this.value10;
    }
    /**
     * seter
     * @param value10 hodnota10
     */
    public void setValue10(int value10) {
        this.value10 = value10;
    }

}
